import { Component } from "@angular/core";


@Component({
  selector: "app-home",
  templateUrl: "./profile.component.html",
})

export class ProfileComponent {
  /*  STUFF TO DO
   * 1. CHECK IF THE USER IS LOGGED IN --> IF NOT SEND THEM BACK TO THE LOG IN PAGE / SIGN UP
   * 2. IF THE USER IS LOGGED IN CHECK AND VERIFY THE JWT TOKEN, IF ITS NOT VERIFIED THEN MAKE THE USER LOG IN AGAIN TO REFRESH THE TOKEN
   * 3. DISPLAY THE USERS NAME AND CURRENT OCCUPATION
   * 4. DISPLAY A DESCREPTION MADE BY THE USER, THIS SHOULD BE POSSIBLE TO EDIT
   */
}
